local specs = {
    {"Warrior", "Protection"},
    {"Warrior", "Fury"},
    {"Warrior", "Arms"},
    {"Warlock", "Demonology"},
    {"Warlock", "Affliction"},
    {"Warlock", "Destruction"},
    {"Priest", "Holy"},
    {"Priest", "Discipline"},
    {"Priest", "Shadow"},
    {"Druid", "Feral"},
    {"Druid", "Restoration"},
    {"Druid", "Balance"},
    {"Paladin", "Holy"},
    {"Paladin", "Retribution"},
    {"Paladin", "Protection"},
    {"Rogue", "Subtlety"},
    {"Rogue", "Combat"},
    {"Rogue", "Assassination"},
    {"Mage", "Fire"},
    {"Mage", "Frost"},
    {"Mage", "Arcane"},
    {"Hunter", "Survival"},
    {"Hunter", "Beast Mastery"},
    {"Hunter", "Marksmanship"},
    {"Shaman", "Elemental"},
    {"Shaman", "Enhancement"},
    {"Shaman", "Restoration"},
}

GoodEPGP.specs = specs